version: '3.8'

services:
  pinecone:
    image: ghcr.io/pinecone-io/pinecone-local:latest
    platform: linux/amd64
    container_name: pinecone-local
    volumes:
      - pinecone-data:/data
    ports:
      - "5080:5080"  # API Service port
      - "5081:5081"  # Controller port
    environment:
      PORT: 5080
      PINECONE_HOST: localhost

volumes:
  pinecone-data:
